language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: IHchLXJzo8DIlr+uU62aeY4AdqTKrGXIpcM8s2BZEdXY0HjPWcaB/r5yhNk7sRrdEO95FMhnITFK4dWn6QSE7TWqXkZOHo0yXeuxSa/MrjAOahnXIiYxOgIfH3D0+ud4sJx697P9iby51YoprZoHRwyGn8LFCXeygad2KclbxEQk2SESuWu1YVxqppJ6W2taHvDToAHkASXBLPWhEEizaiIHsPQw0dgx+ajNyEvTfQQSUBvkFQ9eERRbLaVSvDP7bmsDFnQGz+aUWbegqJiH7kzxAJELrIuj2B9ttrFrO2Gfl4ozznDtp/1BrVfokM48jpJ6JQAqOyj0fatMCEJGXB1MWLcfAptobVFRkU0cE0h3SEBDI8dl2IuS8zN4MUJpLmm2MDoNQmHKt+3z6SO/+KV8UgmmwbgG1p07qzXY6gFyFXI/+9v8IptkkKeei64QWJLtWJJAx8trA0zhydoaq3wiuA84WZIjbqBkHBhUiN1/epeWuxX0Y/efqZbCOLNKjWNpUB6G6f36HXr8R80aXsOGDWNUzn4f5t5+7sR3oiuHvepbX5D8FSk4Cay/7XMe+SPPq9DwGwcNfYS3c5ub6UHm/dLyF7Lf2pFyHFCzelgE0ZJQ70IlVCHJQpG6cflXCZhKFvbIY3Te/QOXzcTobtPZ8aFTsT39b0w/Iv+mJno=
  app: garden-share-be
  on:
    repo: garden-share-08/garden-share-be
    branch: main
  skip_cleanup: 'true'
  run: 
  - bundle exec bundle 
